const packages = {
  async: '^3.2.6',
  bcrypt: '5.1.1',
  'body-parser': '^2.2.0',
  compression: '^1.7.4',
};

const head = {
  'connect-mongo': '^5.1.0',
  consolidate: '^0.15.1',
  'cookie-parser': '^1.4.6',
  csurf: '^1.11.0',
  'dust-makara-helpers': '^4.2.0',
  'dustjs-helpers': '~1.3.0',
  'dustjs-linkedin': '~2.6.0',
  emailjs: '^2.2.0',
  'engine-munger': '^0.2.9',
  express: '^4.21.0',
  'express-session': '^1.18.0',
  fs: '0.0.1-security',
  handlebars: '^4.7.8',
  helmet: '^3.23.3',
  'html-to-text': '^3.3.0',
  imagemagick: '^0.1.3',
  jade: '^1.11.0',
  jsonwebtoken: '9.0.0',
  'kraken-devtools': '^1.4.0',
  'kraken-js': '^2.5.0',
  less: '^3.13.1',
  localizr: '^1.1.0',
  makara: '^2.1.0',
  'method-override': '^2.3.10',
  moment: '^2.30.1',
  'mongodb-backup-fixed': '^1.7.2',
  'mongodb-restore': '^1.6.2',
  mongoose: '8.9.5',
  morgan: '^1.10.0',
  mv: '^2.1.1',
  passport: '0.6.0',
  'passport-facebook': '^2.1.1',
  'passport-github': '^1.1.0',
  'passport-google-oauth': '^1.0.0',
  'passport-local': '^1.0.0',
  'passport-oauth': '^1.0.0',
  'passport-tumblr': '^0.1.2',
  'passport-twitter': '^1.0.4',
  pug: '3.0.3',
  react: '^16.14.0',
  'react-dom': '^16.14.0',
  request: '^2.88.2',
  requirejs: '^2.3.7',
  'serve-static': '^1.14.1',
  underscore: '^1.13.7',
  vash: '^0.12.10',
};
const v2 = {
  'connect-mongo': '5.1.0',
  'cookie-parser': '^1.4.7',
  csurf: '^1.10.0',
  emailjs: '^4.0.3',
  express: '^4.21.2',
  'express-session': '^1.18.1',
  helmet: '7.1.0',
  'html-to-text': '^9.0.5',
  jsonwebtoken: '9.0.2',
  'method-override': '^3.0.0',
  moment: '^2.30.1',
  'mongodb-backup-fixed': '^1.7.2',
  mongoose: '^8.13.2',
  morgan: '^1.10.0',
  passport: '0.7.0',
  'passport-facebook': '2.1.1',
  'passport-github': '1.1.0',
  'passport-google-oauth': '1.0.0',
  'passport-local': '1.0.0',
  'passport-tumblr': '^0.1.2',
  'passport-twitter': '0.1.5',
  react: '18.2.0',
  'react-dom': '18.2.0',
  'serve-static': '2.1.0',
};
// >>>>>>> draft/prod-local-fix-refactor_v2


const scripts = {
  "start": "node server.js",
  "build": "npm run build:js && npm run build:css",
  "build:js": "babel public/templates/react --out-dir public/js/react",
  "build:css": "lessc public/less/app.less public/css/app.min.css --clean-css",
  "watch": "npm-run-all --parallel watch:*",
  "watch:js": "npm run build:js -- --watch",
  "watch:css": "npm run build:css -- --watch",
  "test": "mocha tests/**/*.js",
  "lint": "jshint public/layouts/**/*.js public/views/**/*.js",
  "clean": "rimraf public/css/*.css public/js/react/*.js"
}