'use strict';

import type { Router } from 'express';

import express from 'express';
import * as apiError from '../../middlewares/apiError';
import * as mobileContracts from '../../middlewares/mobileApiContracts';
import { sanitizeContentMiddleware } from '../../middlewares/sanitizeContent';

import attachHome from './home';
import attachTopics from './topics';
import attachArguments from './arguments';
import attachQuestions from './questions';
import attachSearch from './search';
import attachIssues from './issues';
import attachOpinions from './opinions';
import attachAnswers from './answers';
import attachArtifacts from './artifacts';
import attachGroups from './groups';
import attachMembers from './members';
import attachAuth from './auth';
import attachContact from './contact';
import attachAdmin from './admin';
import attachModeration from './moderation';
import attachOutline from './outline';
import attachMonitoring from './monitoring';
import attachRealtime from './realtime';
import attachReactions from './reactions';
import attachNotifications from './notifications';
import attachTimeline from './timeline';
import attachInstall from './install';
import attachPages from './pages';
import { registerEntryRedirectMiddleware } from './entryRedirectMiddleware';
import constants from '../../models/constants';

export = function (router: Router) {
  router.use(apiError.apiEnvelopeMiddleware);
  router.use(mobileContracts.mobileApiContractMiddleware);
  router.use(sanitizeContentMiddleware);

  const homeRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const topicsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const argumentsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const questionsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const searchRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const issuesRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const opinionsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const answersRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const artifactsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const groupsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const membersRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const authRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const contactRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const adminRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const moderationRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const outlineRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const monitoringRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const realtimeRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const reactionsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const notificationsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const timelineRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const installRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const pagesRouter = apiError.wrapAsyncRouter(express.Router()) as Router;

  attachHome(homeRouter);
  registerEntryRedirectMiddleware(topicsRouter, constants.OBJECT_TYPES.topic);
  registerEntryRedirectMiddleware(argumentsRouter, constants.OBJECT_TYPES.argument);
  registerEntryRedirectMiddleware(questionsRouter, constants.OBJECT_TYPES.question);
  registerEntryRedirectMiddleware(answersRouter, constants.OBJECT_TYPES.answer);
  registerEntryRedirectMiddleware(issuesRouter, constants.OBJECT_TYPES.issue);
  registerEntryRedirectMiddleware(opinionsRouter, constants.OBJECT_TYPES.opinion);
  registerEntryRedirectMiddleware(artifactsRouter, constants.OBJECT_TYPES.artifact);
  attachTopics(topicsRouter);
  attachArguments(argumentsRouter);
  attachQuestions(questionsRouter);
  attachSearch(searchRouter);
  attachIssues(issuesRouter);
  attachOpinions(opinionsRouter);
  attachAnswers(answersRouter);
  attachArtifacts(artifactsRouter);
  attachGroups(groupsRouter);
  attachMembers(membersRouter);
  attachAuth(authRouter);
  attachContact(contactRouter);
  attachAdmin(adminRouter);
  attachModeration(moderationRouter);
  attachOutline(outlineRouter);
  attachMonitoring(monitoringRouter);
  attachRealtime(realtimeRouter);
  attachReactions(reactionsRouter);
  attachNotifications(notificationsRouter);
  attachTimeline(timelineRouter);
  attachInstall(installRouter);
  attachPages(pagesRouter);

  router.use('/home', homeRouter);
  router.use('/topics', topicsRouter);
  router.use('/arguments', argumentsRouter);
  router.use('/questions', questionsRouter);
  router.use('/search', searchRouter);
  router.use('/issues', issuesRouter);
  router.use('/opinions', opinionsRouter);
  router.use('/answers', answersRouter);
  router.use('/artifacts', artifactsRouter);
  router.use('/groups', groupsRouter);
  router.use('/members', membersRouter);
  router.use('/auth', authRouter);
  router.use('/contact', contactRouter);
  router.use('/admin', adminRouter);
  router.use('/moderation', moderationRouter);
  router.use('/outline', outlineRouter);
  router.use('/monitoring', monitoringRouter);
  router.use('/realtime', realtimeRouter);
  router.use('/reactions', reactionsRouter);
  router.use('/notifications', notificationsRouter);
  router.use('/timeline', timelineRouter);
  router.use('/install', installRouter);
  router.use('/pages', pagesRouter);
};
