'use strict';

import type { Router } from 'express';

import express from 'express';
import * as apiError from '../../middlewares/apiError';
import * as mobileContracts from '../../middlewares/mobileApiContracts';
import { sanitizeContentMiddleware } from '../../middlewares/sanitizeContent';

import attachHome from './home';
import attachApplicationContext from './applicationContext';
import attachTopics from './topics';
import attachArguments from './arguments';
import attachQuestions from './questions';
import attachSearch from './search';
import attachIssues from './issues';
import attachOpinions from './opinions';
import attachAnswers from './answers';
import attachArtifacts from './artifacts';
import attachGroups from './groups';
import attachMembers from './members';
import attachAuth from './auth';
import attachContact from './contact';
import attachAdmin from './admin';
import attachModeration from './moderation';
import attachOutline from './outline';
import attachMonitoring from './monitoring';
import attachRealtime from './realtime';
import attachReactions from './reactions';
import attachNotifications from './notifications';
import attachTimeline from './timeline';
import attachInstall from './install';
import attachPages from './pages';
import attachAnonymousContributions from './anonymousContributions';
import attachCivic from './civic';
import { registerEntryRedirectMiddleware } from './entryRedirectMiddleware';
import constants from '../../models/constants';
import { requireContributorOnboarding } from '../../middlewares/onboarding';
import { enforceApiClientScope } from '../../middlewares/apiClientScopes';
import attachAgent from './agent';
import attachEpistemic from './epistemic';
import attachTranslations from './translations';
import { apiVersionPolicy } from '../../middlewares/apiVersionPolicy';
import { enforceAgentMutationReliability } from '../../middlewares/agentMutationReliability';

export = function (router: Router) {
  router.use(apiVersionPolicy);
  router.use(apiError.apiEnvelopeMiddleware);
  router.use(mobileContracts.mobileApiContractMiddleware);
  router.use(sanitizeContentMiddleware);
  router.use(enforceApiClientScope);
  router.use(enforceAgentMutationReliability);

  const homeRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const applicationContextRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const topicsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const argumentsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const questionsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const searchRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const issuesRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const opinionsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const answersRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const artifactsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const groupsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const membersRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const authRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const contactRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const adminRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const moderationRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const outlineRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const monitoringRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const realtimeRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const reactionsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const notificationsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const timelineRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const installRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const pagesRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const anonymousContributionsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const civicRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const explicitCivicRouter = apiError.wrapAsyncRouter(express.Router({ mergeParams: true })) as Router;
  const agentRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const epistemicRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const translationsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;

  [topicsRouter, argumentsRouter, questionsRouter, answersRouter, issuesRouter, opinionsRouter, artifactsRouter]
    .forEach((entryRouter) => entryRouter.use(requireContributorOnboarding));
  outlineRouter.use(requireContributorOnboarding);

  attachHome(homeRouter);
  attachApplicationContext(applicationContextRouter);
  registerEntryRedirectMiddleware(topicsRouter, constants.OBJECT_TYPES.topic);
  registerEntryRedirectMiddleware(argumentsRouter, constants.OBJECT_TYPES.argument);
  registerEntryRedirectMiddleware(questionsRouter, constants.OBJECT_TYPES.question);
  registerEntryRedirectMiddleware(answersRouter, constants.OBJECT_TYPES.answer);
  registerEntryRedirectMiddleware(issuesRouter, constants.OBJECT_TYPES.issue);
  registerEntryRedirectMiddleware(opinionsRouter, constants.OBJECT_TYPES.opinion);
  registerEntryRedirectMiddleware(artifactsRouter, constants.OBJECT_TYPES.artifact);
  attachTopics(topicsRouter);
  attachArguments(argumentsRouter);
  attachQuestions(questionsRouter);
  attachSearch(searchRouter);
  attachIssues(issuesRouter);
  attachOpinions(opinionsRouter);
  attachAnswers(answersRouter);
  attachArtifacts(artifactsRouter);
  attachGroups(groupsRouter);
  attachMembers(membersRouter);
  attachAuth(authRouter);
  attachContact(contactRouter);
  attachAdmin(adminRouter);
  attachModeration(moderationRouter);
  attachOutline(outlineRouter);
  attachMonitoring(monitoringRouter);
  attachRealtime(realtimeRouter);
  attachReactions(reactionsRouter);
  attachNotifications(notificationsRouter);
  attachTimeline(timelineRouter);
  attachInstall(installRouter);
  attachPages(pagesRouter);
  attachAnonymousContributions(anonymousContributionsRouter);
  [civicRouter, explicitCivicRouter].forEach(attachCivic);
  attachAgent(agentRouter);
  attachEpistemic(epistemicRouter);
  attachTranslations(translationsRouter);

  router.use('/home', homeRouter);
  router.use('/application-context', applicationContextRouter);
  router.use('/topics', topicsRouter);
  router.use('/arguments', argumentsRouter);
  router.use('/questions', questionsRouter);
  router.use('/search', searchRouter);
  router.use('/issues', issuesRouter);
  router.use('/opinions', opinionsRouter);
  router.use('/answers', answersRouter);
  router.use('/artifacts', artifactsRouter);
  router.use('/groups', groupsRouter);
  router.use('/members', membersRouter);
  router.use('/auth', authRouter);
  router.use('/contact', contactRouter);
  router.use('/admin', adminRouter);
  router.use('/moderation', moderationRouter);
  router.use('/outline', outlineRouter);
  router.use('/monitoring', monitoringRouter);
  router.use('/realtime', realtimeRouter);
  router.use('/reactions', reactionsRouter);
  router.use('/notifications', notificationsRouter);
  router.use('/timeline', timelineRouter);
  router.use('/install', installRouter);
  router.use('/pages', pagesRouter);
  router.use('/anonymous-contributions', anonymousContributionsRouter);
  router.use('/civic', civicRouter);
  router.use('/tenants/:tenantId/civic', explicitCivicRouter);
  router.use('/agent', agentRouter);
  router.use('/epistemic', epistemicRouter);
  router.use('/translations', translationsRouter);
};
