'use strict';

import type { Router } from 'express';

const express = require('express') as typeof import('express');
import * as apiError from '../../middlewares/apiError';
import * as mobileContracts from '../../middlewares/mobileApiContracts';
import { sanitizeContentMiddleware } from '../../middlewares/sanitizeContent';

module.exports = function (router: Router) {
  router.use(apiError.apiEnvelopeMiddleware);
  router.use(mobileContracts.mobileApiContractMiddleware);
  router.use(sanitizeContentMiddleware);

  const homeRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const topicsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const argumentsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const questionsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const searchRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const issuesRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const opinionsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const answersRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const artifactsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const groupsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const membersRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const authRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const contactRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const adminRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const moderationRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const outlineRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const monitoringRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const realtimeRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const reactionsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const notificationsRouter = apiError.wrapAsyncRouter(express.Router()) as Router;
  const timelineRouter = apiError.wrapAsyncRouter(express.Router()) as Router;

  (require('./home') as (routerArg: Router) => void)(homeRouter);
  (require('./topics') as (routerArg: Router) => void)(topicsRouter);
  (require('./arguments') as (routerArg: Router) => void)(argumentsRouter);
  (require('./questions') as (routerArg: Router) => void)(questionsRouter);
  (require('./search') as (routerArg: Router) => void)(searchRouter);
  (require('./issues') as (routerArg: Router) => void)(issuesRouter);
  (require('./opinions') as (routerArg: Router) => void)(opinionsRouter);
  (require('./answers') as (routerArg: Router) => void)(answersRouter);
  (require('./artifacts') as (routerArg: Router) => void)(artifactsRouter);
  (require('./groups') as (routerArg: Router) => void)(groupsRouter);
  (require('./members') as (routerArg: Router) => void)(membersRouter);
  (require('./auth') as (routerArg: Router) => void)(authRouter);
  (require('./contact') as (routerArg: Router) => void)(contactRouter);
  (require('./admin') as (routerArg: Router) => void)(adminRouter);
  (require('./moderation') as (routerArg: Router) => void)(moderationRouter);
  (require('./outline') as (routerArg: Router) => void)(outlineRouter);
  (require('./monitoring') as (routerArg: Router) => void)(monitoringRouter);
  (require('./realtime') as (routerArg: Router) => void)(realtimeRouter);
  (require('./reactions') as (routerArg: Router) => void)(reactionsRouter);
  (require('./notifications') as (routerArg: Router) => void)(notificationsRouter);
  (require('./timeline') as (routerArg: Router) => void)(timelineRouter);

  router.use('/home', homeRouter);
  router.use('/topics', topicsRouter);
  router.use('/arguments', argumentsRouter);
  router.use('/questions', questionsRouter);
  router.use('/search', searchRouter);
  router.use('/issues', issuesRouter);
  router.use('/opinions', opinionsRouter);
  router.use('/answers', answersRouter);
  router.use('/artifacts', artifactsRouter);
  router.use('/groups', groupsRouter);
  router.use('/members', membersRouter);
  router.use('/auth', authRouter);
  router.use('/contact', contactRouter);
  router.use('/admin', adminRouter);
  router.use('/moderation', moderationRouter);
  router.use('/outline', outlineRouter);
  router.use('/monitoring', monitoringRouter);
  router.use('/realtime', realtimeRouter);
  router.use('/reactions', reactionsRouter);
  router.use('/notifications', notificationsRouter);
  router.use('/timeline', timelineRouter);
};
